# Generated by Django 4.2.3 on 2023-07-25 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Режисер')),
                ('slug', models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('genre', models.CharField(max_length=200, verbose_name='Жанр')),
                ('year', models.IntegerField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('info', models.TextField(blank=True, verbose_name='Инфо')),
                ('grade_kinopoisk', models.FloatField(blank=True)),
                ('grade_imdb', models.FloatField(blank=True)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rec.director')),
            ],
        ),
    ]
